package generator

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/malinatrash/envify/internal/parser"
)

func Write(outputPath, typeName string, entries []parser.EnvEntry) error {
	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)

	fmt.Fprintf(w, "# Generated by envify from %s\n", typeName)
	fmt.Fprintf(w, "# %s\n\n", time.Now().Format("2006-01-02"))

	for _, e := range entries {
		var meta []string
		if e.Required {
			meta = append(meta, "required")
		}
		if e.Masked {
			meta = append(meta, "sensitive")
		}

		if len(meta) > 0 {
			fmt.Fprintf(w, "# %s\n", strings.Join(meta, ", "))
		}

		if e.Default != "" {
			fmt.Fprintf(w, "%s=%s\n", e.Key, e.Default)
		} else {
			fmt.Fprintf(w, "%s=\n", e.Key)
		}
	}

	return w.Flush()
}
